[package]
name = "azchar"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "azchar"
path = "azchar-server/src/main.rs"

[workspace]
members = [
  "azchar-config",
  "azchar-database",
  "azchar-error",
  "azchar-server",
]
